import Foundation

enum ParkingInsightTips {
    static let tips: [String] = [
        "Save the spot the moment you park—future you will thank you.",
        "Add floor and zone when garages repeat levels.",
        "A short note beats a long search in crowded lots.",
        "Favorites help you reuse reliable locations faster.",
        "Street parking benefits from a visible landmark in the title.",
        "Airport lots change often—capture the shuttle stop name.",
        "Mall parking is easier with the nearest store entrance.",
        "Office garages are simpler with pillar codes.",
        "Reminders reduce surprise fees and time limits.",
        "Photos help when numbers are hard to read at night.",
        "Vehicle nicknames keep family cars organized.",
        "Ending a session keeps stats honest and calm.",
        "Reactivating a spot is perfect when plans change.",
        "Duplicate a record to plan a similar trip next week.",
        "Search works across title, address, and notes together.",
        "Filters narrow history without losing older saves.",
        "Sorting by active puts your current session on top.",
        "Emerald accents stay readable in bright daylight.",
        "Warm amber feels steady during rushed exits.",
        "Violet bloom adds contrast on graphite backgrounds.",
        "A clear title is faster than scanning the whole card.",
        "Spot numbers matter most in numbered decks.",
        "Zones help when maps repeat similar levels.",
        "Garage sessions average longer—plan reminders earlier.",
        "Street sessions are shorter on average—tighter reminders help.",
        "Weekly counts show how often you move between places.",
        "Monthly totals highlight routine versus travel weeks.",
        "Most-used type reveals your real-world default habit.",
        "Average duration reflects completed sessions only.",
        "Active count should usually stay at zero or one.",
        "Clearing history is permanent—export mentally first.",
        "Reset onboarding is useful after sharing a demo device.",
        "Default parking type speeds up repeat workflows.",
        "Default reminder offsets match typical errands.",
        "Copy address when sharing a pin with someone else.",
        "Maps opens best with full street context in the address field.",
        "Inactive records remain useful for reference trips.",
        "Favorites surface patterns you trust over time.",
        "Markers make cards recognizable at a glance.",
        "Parking time anchors disputes and receipts.",
        "Created timestamps help when auditing old visits.",
        "Editing updates persistence immediately—no extra save step.",
        "Deleting asks for confirmation to prevent accidents.",
        "Find Car focuses on the essentials under stress.",
        "Home highlights the session that matters right now.",
        "Stats stay empty until you have enough real sessions.",
        "Settings tune the app without cluttering daily screens.",
        "Offline-first means garages with weak signal still work.",
        "Consistency beats complexity when you are in a hurry.",
        "Park Pin is built for calm returns, not noisy dashboards."
    ]
}
